# @package _global_

method: df
mode: dr
seed: 1
verbose: True
n_folds: 2

model:
    output_dim: 20
    hidden_dim: [20, 20]
    sigma_init: 2.0
    lamb: 20.0
    learn_sigma: False

propensity_score_model:
    _target_: sklearn.ensemble.RandomForestClassifier
    max_depth: 4

train:
    lr_or: 2e-2
    lr_fi: 2e-2
    batch_size_or: 10000
    batch_size_fi: 10000
    epoch_or: 6000
    epoch_fi: 1000
    valid_size_or: null
    valid_size_fi: null
    patience_or: null
    patience_fi: null

test:
    num_bin: 1000
